	git rm    LICENSE
	git rm    README.md
	git rm    package.json
	git rm    public/favicon.ico
	git rm    public/ghost.png
	git rm    public/index.html
	git rm    public/manifest.json
	git rm    src/index.js
	git rm    src/index.scss
	git rm    src/modules/App/App.js
	git rm    src/modules/App/App.scss
	git rm    src/modules/App/App.test.js
	git rm    src/modules/App/components/Footer/Footer.js
	git rm    src/modules/App/components/Header/Header.js
	git rm    src/modules/Lessons/1_LessonJSX/LessonJSX.js
	git rm    src/modules/Lessons/1_LessonJSX/LessonJSX.scss
	git rm    src/modules/Lessons/1_LessonJSX/components/JSXAttributes.js
	git rm    src/modules/Lessons/1_LessonJSX/components/JSXExpressions.js
	git rm    src/modules/Lessons/1_LessonJSX/components/JSXIntro.js
	git rm    src/modules/Lessons/2_LessonElements/LessonElements.js
	git rm    src/modules/Lessons/2_LessonElements/components/EleIntro.js
	git rm    src/modules/Lessons/2_LessonElements/components/EleRender.js
	git rm    src/modules/Lessons/2_LessonElements/components/EleUpdation.js
	git rm    src/modules/Lessons/2_LessonElements/components/SimpleReactEle.js
	git rm    src/modules/Lessons/3_LessonCompProps/Account/Account.js
	git rm    src/modules/Lessons/3_LessonCompProps/Account/Profile/Profile.js
	git rm    src/modules/Lessons/3_LessonCompProps/Account/Profile/Profile.scss
	git rm    src/modules/Lessons/3_LessonCompProps/Account/Profile/ProfileEdit/ProfileEdit.js
	git rm    src/modules/Lessons/3_LessonCompProps/Account/Profile/ProfileEdit/ProfileEdit.scss
	git rm    src/modules/Lessons/3_LessonCompProps/Account/Profile/ProfileView/ProfileView.js
	git rm    src/modules/Lessons/3_LessonCompProps/CompPropsIntro.js
	git rm    src/modules/Lessons/3_LessonCompProps/LessonCompProps.js
	git rm    src/modules/Lessons/4_LessonStateLifeHooks/LessonStateLifeHooks.js
	git rm    src/modules/Lessons/4_LessonStateLifeHooks/components/HooksList.js
	git rm    src/modules/Lessons/4_LessonStateLifeHooks/components/LessonHooks.js
	git rm    src/modules/Lessons/4_LessonStateLifeHooks/components/LessonState.js
	git rm    src/modules/Lessons/4_LessonStateLifeHooks/components/LessonState.scss
	git rm    src/modules/Lessons/4_LessonStateLifeHooks/components/StateLifeHooksIntro.js
	git rm    src/modules/Lessons/5_LessonConditionalRenders/LessonConditionalRenders.js
	git rm    src/modules/Lessons/5_LessonConditionalRenders/components/AssignmentDetails.js
	git rm    src/modules/Lessons/5_LessonConditionalRenders/components/ConditionalRenderIntro.js
	git rm    src/modules/Lessons/5_LessonConditionalRenders/components/ConditionalRenderPractice.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/LessonStateLiftup.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/LessonStateLiftup.scss
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/StateLiftupIntro.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part1/BoilingNotice.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part1/TemperatureCalculator.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part2/BoilingNotice.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part2/TempInput.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part2/TemperatureCalculator.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part3/BoilingNotice.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part3/TempInput.js
	git rm    src/modules/Lessons/6_LessonStateLiftup/components/tempCalculators/part3/TemperatureCalculator.js
	git rm    src/modules/Lessons/7_LessonContainerPresentational/LessonContainerPresentational.js
	git rm    src/modules/Lessons/7_LessonContainerPresentational/components/LessonContPresIntro.js
	git rm    src/modules/Lessons/7_LessonContainerPresentational/components/Loader.js
	git rm    src/modules/Lessons/7_LessonContainerPresentational/components/SearchResults.js
	git rm    src/modules/Lessons/8_LessonUserData/LessonUserData.js
	git rm    src/modules/Lessons/8_LessonUserData/components/PracticeUserData.js
	git rm    src/modules/Lessons/8_LessonUserData/components/PracticeUserData.scss
	git rm    src/modules/Lessons/8_LessonUserData/components/UserDataIntro.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/LessonAPIIntegration.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/APIIntegrationIntro.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/PracticeAPIIntegration.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/PracticeAPIIntegration.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part1/GitDashboard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part2/ErrorLoading/ErrorLoading.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part2/ErrorLoading/ErrorLoading.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part2/GitDashboard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part2/GitDashboard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part2/UserCard/UserCard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part2/UserCard/UserCard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/ErrorLoading/ErrorLoading.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/ErrorLoading/ErrorLoading.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/GitDashboard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/GitDashboard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/Searchbox/Searchbox.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/Searchbox/Searchbox.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/UserCard/UserCard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part3/UserCard/UserCard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/Card/Card.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/ErrorLoading/ErrorLoading.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/ErrorLoading/ErrorLoading.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/GitDashboard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/GitDashboard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/RepoCard/RepoCard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/RepoCard/RepoCard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/Searchbox/Searchbox.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/Searchbox/Searchbox.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/UserCard/UserCard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part4/UserCard/UserCard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/Card/Card.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/ErrorLoading/ErrorLoading.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/ErrorLoading/ErrorLoading.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/GitDashboard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/GitDashboard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/RepoCard/RepoCard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/RepoCard/RepoCard.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/Searchbox/Searchbox.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/Searchbox/Searchbox.scss
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/UserCard/UserCard.js
	git rm    src/modules/Lessons/9_LessonAPIIntegration/components/part5/UserCard/UserCard.scss
	git rm    src/modules/Lessons/Lessons.js
	git rm    src/modules/Lessons/Lessons.scss
	git rm    src/static/img/logo-pacman.svg
	git rm    src/util/countries.js
	git rm    src/util/fonts.js
	git rm    src/util/resultsList.js

